id: P9B336FBB
initial_creation_type: ocr
source_metadata:
  volumes:
    84a22cc43d95440aacea9da4f121c2fb:
      base_file: v077.txt
      image_group_id: I1PD95922
      title: ཉི་ཤུ་པའི་འགྲེལ་པ།
      total_pages: 1517
      volume_number: 77
